version: '3.8'

services:
  banco_de_dados:
    image: postgres:15  
    container_name: banco_de_dados
    environment:
      POSTGRES_USER: jogador
      POSTGRES_PASSWORD: 22312
      POSTGRES_DB: jogo
    ports:
      - "6000:6000"    
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      
  

volumes:
  postgres_data:
